/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary': '#00545e',
        'primary-container': '#0b6e7a',
        'on-primary': '#ffffff',
        'on-primary-container': '#9feefb',
        'primary-fixed': '#a0effd',
        'primary-fixed-dim': '#84d3e0',
        'secondary': '#546162',
        'secondary-container': '#d8e5e7',
        'on-secondary': '#ffffff',
        'surface': '#f7fafa',
        'surface-dim': '#d7dadb',
        'surface-bright': '#f7fafa',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f1f4f5',
        'surface-container': '#ebeeef',
        'surface-container-high': '#e6e9e9',
        'surface-container-highest': '#e0e3e3',
        'on-surface': '#181c1d',
        'on-surface-variant': '#3f484a',
        'outline': '#6f797b',
        'outline-variant': '#bec8ca',
        'inverse-surface': '#2d3132',
        'inverse-on-surface': '#eef1f2',
        'background': '#f7fafa',
        'on-background': '#181c1d',
        'error': '#ba1a1a',
        'tertiary': '#72400f',
        'tertiary-container': '#8e5725',
        'on-tertiary-container': '#ffdbc0',
      },
      fontFamily: {
        'display': ['Playfair Display', 'serif'],
        'headline': ['Playfair Display', 'serif'],
        'body': ['Inter', 'sans-serif'],
        'label': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '600' }],
      },
      borderRadius: {
        'DEFAULT': '0.5rem',
        'lg': '1rem',
        'xl': '1.5rem',
        'full': '9999px',
      },
      boxShadow: {
        'glass': '0 4px 30px rgba(11, 110, 122, 0.08)',
        'card': '0 8px 32px rgba(11, 110, 122, 0.12)',
      },
      backgroundImage: {
        'hero-gradient': 'linear-gradient(135deg, #F8FAFB 0%, #E8F5F7 100%)',
      },
    },
  },
  plugins: [],
}